[package]
name = "idgen"
version = "0.1.0"
edition = "2021"
author = "Jordan Bravo, jordan.bravo.cc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
cuid2 = "0.1.2"
